services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: YOUR_USER
      POSTGRES_PASSWORD: YOU_PASS
      POSTGRES_DB: api_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api_auth
      SPRING_DATASOURCE_USERNAME: YOUR_USER
      SPRING_DATASOURCE_PASSWORD: YOUR_PASS
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
